swagger: "2.0"
info:
  description: "This API returns famous movie quotes"
  version: "1.0.0"
  title: "Movie Quote API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@movie.quotes.api"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "movie.quotes.api"
basePath: "/v1"
tags:
  - name: "quote"
    description: "Random movie quotes"
    externalDocs:
      description: "Find out more"
      url: "http://movie-quotes-api"
schemes:
  - "https"
  - "http"
paths:
  /quote:
    get:
      tags:
        - "quote"
      summary: "Get a random movie quote"
      description: ""
      operationId: "getQuote"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/MovieQuote"
definitions:
  MovieQuote:
    type: "object"
    required:
      - "id"
      - "quote"
      - "movie"
      - "year"
    properties:
      id:
        type: "integer"
        format: "int64"
      quote:
        type: "string"
        example: "I'm your huckleberry"
      movie:
        type: "string"
        example: "TOMBSTONE"
      year:
        type: "string"
        example: "1993"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"